/* ============================================================
   mock-data.js — Sample Bible verses (WEB — public domain)
   Covers Genesis 1-2, Psalm 23, John 1 & 3, Romans 8
   ============================================================ */

const VERSES = {
  'GEN.1.1':  'In the beginning, God created the heavens and the earth.',
  'GEN.1.2':  "The earth was formless and empty. Darkness was on the surface of the deep and God's Spirit was hovering over the surface of the waters.",
  'GEN.1.3':  'God said, "Let there be light," and there was light.',
  'GEN.1.4':  'God saw the light, and saw that it was good. God divided the light from the darkness.',
  'GEN.1.5':  'God called the light "day", and the darkness he called "night". There was evening and there was morning, the first day.',
  'GEN.1.6':  'God said, "Let there be an expanse in the middle of the waters, and let it divide the waters from the waters."',
  'GEN.1.7':  'God made the expanse, and divided the waters which were under the expanse from the waters which were above the expanse; and it was so.',
  'GEN.1.8':  'God called the expanse "sky". There was evening and there was morning, a second day.',
  'GEN.1.9':  'God said, "Let the waters under the sky be gathered together to one place, and let the dry land appear;" and it was so.',
  'GEN.1.10': 'God called the dry land "earth", and the gathering together of the waters he called "seas". God saw that it was good.',
  'GEN.1.11': 'God said, "Let the earth yield grass, herbs yielding seeds, and fruit trees bearing fruit after their kind, with their seeds in it, on the earth;" and it was so.',
  'GEN.1.12': 'The earth yielded grass, herbs yielding seed after their kind, and trees bearing fruit, with their seeds in it, after their kind; and God saw that it was good.',
  'GEN.1.13': 'There was evening and there was morning, a third day.',
  'GEN.1.14': 'God said, "Let there be lights in the expanse of the sky to divide the day from the night; and let them be for signs to mark seasons, days, and years."',
  'GEN.1.15': '"and let them be for lights in the expanse of the sky to give light on the earth;" and it was so.',
  'GEN.1.16': 'God made the two great lights: the greater light to rule the day, and the lesser light to rule the night. He also made the stars.',
  'GEN.1.17': 'God set them in the expanse of the sky to give light to the earth,',
  'GEN.1.18': 'and to rule over the day and over the night, and to divide the light from the darkness. God saw that it was good.',
  'GEN.1.19': 'There was evening and there was morning, a fourth day.',
  'GEN.1.20': 'God said, "Let the waters abound with living creatures, and let birds fly above the earth in the open expanse of the sky."',
  'GEN.1.21': 'God created the large sea creatures, and every living creature that moves, with which the waters swarmed, after their kind, and every winged bird after its kind. God saw that it was good.',
  'GEN.1.22': 'God blessed them, saying, "Be fruitful, and multiply, and fill the waters in the seas, and let birds multiply on the earth."',
  'GEN.1.23': 'There was evening and there was morning, a fifth day.',
  'GEN.1.24': 'God said, "Let the earth produce living creatures after their kind, livestock, creeping things, and animals of the earth after their kind;" and it was so.',
  'GEN.1.25': 'God made the animals of the earth after their kind, and the livestock after their kind, and everything that creeps on the ground after its kind. God saw that it was good.',
  'GEN.1.26': 'God said, "Let us make man in our image, after our likeness: and let them have dominion over the fish of the sea, and over the birds of the sky, and over the livestock, and over all the earth, and over every creeping thing that creeps on the earth."',
  'GEN.1.27': "God created man in his own image. In God's image he created him; male and female he created them.",
  'GEN.1.28': 'God blessed them. God said to them, "Be fruitful, multiply, fill the earth, and subdue it. Have dominion over the fish of the sea, over the birds of the sky, and over every living thing that moves on the earth."',
  'GEN.1.29': 'God said, "Behold, I have given you every herb yielding seed, which is on the surface of all the earth, and every tree, which bears fruit yielding seed. It will be your food.',
  'GEN.1.30': 'To every animal of the earth, and to every bird of the sky, and to everything that creeps on the earth, in which there is life, I have given every green herb for food;" and it was so.',
  'GEN.1.31': 'God saw everything that he had made, and, behold, it was very good. There was evening and there was morning, a sixth day.',
  'GEN.2.1':  'The heavens and the earth were finished, and all their vast array.',
  'GEN.2.2':  'On the seventh day God finished his work which he had done; and he rested on the seventh day from all his work which he had done.',
  'GEN.2.3':  'God blessed the seventh day, and made it holy, because he rested in it from all his work of creation which he had done.',
  'GEN.2.4':  'This is the history of the generations of the heavens and of the earth when they were created, in the day that Yahweh God made the earth and the heavens.',
  'GEN.2.5':  'No plant of the field was yet in the earth, and no herb of the field had yet sprung up; for Yahweh God had not caused it to rain on the earth. There was not a man to till the ground,',
  'GEN.2.6':  'but a mist went up from the earth, and watered the whole surface of the ground.',
  'GEN.2.7':  "Yahweh God formed man from the dust of the ground, and breathed into his nostrils the breath of life; and man became a living soul.",
  'GEN.2.8':  'Yahweh God planted a garden eastward, in Eden, and there he put the man whom he had formed.',
  'GEN.2.9':  'Out of the ground Yahweh God made every tree to grow that is pleasant to the sight, and good for food, including the tree of life in the middle of the garden and the tree of the knowledge of good and evil.',
  'GEN.2.10': 'A river went out of Eden to water the garden; and from there it was parted, and became the source of four rivers.',
  'GEN.2.15': 'Yahweh God took the man, and put him into the garden of Eden to cultivate and keep it.',
  'GEN.2.16': 'Yahweh God commanded the man, saying, "You may freely eat of every tree of the garden;',
  'GEN.2.17': 'but you shall not eat of the tree of the knowledge of good and evil; for in the day that you eat of it, you will surely die."',
  'GEN.2.18': 'Yahweh God said, "It is not good for the man to be alone. I will make him a helper comparable to him."',
  'GEN.2.24': 'Therefore a man will leave his father and his mother, and will join with his wife, and they will be one flesh.',
  'PSA.23.1': 'Yahweh is my shepherd; I shall lack nothing.',
  'PSA.23.2': 'He makes me lie down in green pastures. He leads me beside still waters.',
  'PSA.23.3': "He restores my soul. He guides me in the paths of righteousness for his name's sake.",
  'PSA.23.4': "Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me. Your rod and your staff, they comfort me.",
  'PSA.23.5': 'You prepare a table before me in the presence of my enemies. You anoint my head with oil. My cup runs over.',
  'PSA.23.6': "Surely goodness and loving kindness shall follow me all the days of my life, and I will dwell in Yahweh's house forever.",
  'JHN.1.1':  'In the beginning was the Word, and the Word was with God, and the Word was God.',
  'JHN.1.2':  'The same was in the beginning with God.',
  'JHN.1.3':  'All things were made through him. Without him, nothing was made that has been made.',
  'JHN.1.4':  'In him was life, and the life was the light of men.',
  'JHN.1.5':  "The light shines in the darkness, and the darkness hasn't overcome it.",
  'JHN.1.6':  'There came a man sent from God, whose name was John.',
  'JHN.1.7':  'The same came as a witness, that he might testify about the light, that all might believe through him.',
  'JHN.1.8':  'He was not the light, but was sent that he might testify about the light.',
  'JHN.1.9':  'The true light that enlightens everyone was coming into the world.',
  'JHN.1.10': "He was in the world, and the world was made through him, and the world didn't recognize him.",
  'JHN.1.11': "He came to his own, and those who were his own didn't receive him.",
  'JHN.1.12': "But as many as received him, to them he gave the right to become God's children, to those who believe in his name:",
  'JHN.1.13': 'who were born not of blood, nor of the will of the flesh, nor of the will of man, but of God.',
  'JHN.1.14': 'The Word became flesh and lived among us. We saw his glory, such glory as of the one and only Son of the Father, full of grace and truth.',
  'JHN.1.15': "John testified about him. He cried out, saying, \"This was he of whom I said, 'He who comes after me has surpassed me, for he was before me.'\"",
  'JHN.1.16': 'From his fullness we all received grace upon grace.',
  'JHN.1.17': 'For the law was given through Moses. Grace and truth were realized through Jesus Christ.',
  'JHN.1.18': 'No one has seen God at any time. The one and only Son, who is in the bosom of the Father, he has declared him.',
  'JHN.3.1':  'Now there was a man of the Pharisees named Nicodemus, a ruler of the Jews.',
  'JHN.3.2':  'The same came to him by night and said to him, "Rabbi, we know that you are a teacher come from God, for no one can do these signs that you do, unless God is with him."',
  'JHN.3.3':  'Jesus answered him, "Most certainly, I tell you, unless one is born anew, he can\'t see God\'s Kingdom."',
  'JHN.3.4':  "Nicodemus said to him, \"How can a man be born when he is old? Can he enter a second time into his mother's womb and be born?\"",
  'JHN.3.5':  "Jesus answered, \"Most certainly I tell you, unless one is born of water and spirit, he can't enter into God's Kingdom.",
  'JHN.3.6':  'That which is born of the flesh is flesh. That which is born of the Spirit is spirit.',
  'JHN.3.7':  "Don't marvel that I said to you, 'You must be born anew.'",
  'JHN.3.8':  "The wind blows where it wants to, and you hear its sound, but don't know where it comes from and where it is going. So is everyone who is born of the Spirit.\"",
  'JHN.3.9':  'Nicodemus answered him, "How can these things be?"',
  'JHN.3.10': "Jesus answered him, \"Are you the teacher of Israel, and don't understand these things?",
  'JHN.3.11': "Most certainly I tell you, we speak that which we know, and testify of that which we have seen, and you don't receive our witness.",
  'JHN.3.12': "If I told you earthly things and you don't believe, how will you believe if I tell you heavenly things?",
  'JHN.3.13': 'No one has ascended into heaven but he who descended out of heaven, the Son of Man, who is in heaven.',
  'JHN.3.14': 'As Moses lifted up the serpent in the wilderness, even so must the Son of Man be lifted up,',
  'JHN.3.15': 'that whoever believes in him should not perish, but have eternal life.',
  'JHN.3.16': 'For God so loved the world, that he gave his one and only Son, that whoever believes in him should not perish, but have eternal life.',
  'JHN.3.17': "For God didn't send his Son into the world to judge the world, but that the world should be saved through him.",
  'JHN.3.18': "He who believes in him is not judged. He who doesn't believe has been judged already, because he has not believed in the name of the one and only Son of God.",
  'JHN.3.19': 'This is the judgment, that the light has come into the world, and men loved the darkness rather than the light, for their works were evil.',
  'JHN.3.20': "For everyone who does evil hates the light and doesn't come to the light, lest his works would be exposed.",
  'JHN.3.21': 'But he who does the truth comes to the light, that his works may be revealed, that they have been done in God."',
  'ROM.8.1':  "There is therefore now no condemnation to those who are in Christ Jesus, who don't walk according to the flesh, but according to the Spirit.",
  'ROM.8.2':  'For the law of the Spirit of life in Christ Jesus made me free from the law of sin and of death.',
  'ROM.8.3':  "For what the law couldn't do, in that it was weak through the flesh, God did, sending his own Son in the likeness of sinful flesh and for sin, he condemned sin in the flesh,",
  'ROM.8.4':  'that the ordinance of the law might be fulfilled in us, who walk not after the flesh, but after the Spirit.',
  'ROM.8.5':  'For those who live according to the flesh set their minds on the things of the flesh, but those who live according to the Spirit, the things of the Spirit.',
  'ROM.8.6':  'For the mind of the flesh is death, but the mind of the Spirit is life and peace;',
  'ROM.8.7':  "because the mind of the flesh is hostile toward God; for it is not subject to God's law, neither indeed can it be.",
  'ROM.8.8':  "Those who are in the flesh can't please God.",
  'ROM.8.9':  "But you are not in the flesh but in the Spirit, if it is so that the Spirit of God dwells in you. But if any man doesn't have the Spirit of Christ, he is not his.",
  'ROM.8.10': 'If Christ is in you, the body is dead because of sin, but the spirit is alive because of righteousness.',
  'ROM.8.11': 'But if the Spirit of him who raised up Jesus from the dead dwells in you, he who raised up Christ Jesus from the dead will also give life to your mortal bodies through his Spirit who dwells in you.',
  'ROM.8.12': 'So then, brothers, we are debtors, not to the flesh, to live after the flesh.',
  'ROM.8.13': 'For if you live after the flesh, you must die; but if by the Spirit you put to death the deeds of the body, you will live.',
  'ROM.8.14': 'For as many as are led by the Spirit of God, these are children of God.',
  'ROM.8.15': 'For you didn\'t receive the spirit of bondage again to fear, but you received the Spirit of adoption, by whom we cry, "Abba! Father!"',
  'ROM.8.16': 'The Spirit himself testifies with our spirit that we are children of God;',
  'ROM.8.17': 'and if children, then heirs — heirs of God and joint heirs with Christ, if indeed we suffer with him, that we may also be glorified with him.',
  'ROM.8.18': 'For I consider that the sufferings of this present time are not worth comparing with the glory which will be revealed toward us.',
  'ROM.8.28': 'We know that all things work together for good for those who love God, for those who are called according to his purpose.',
  'ROM.8.31': 'What then shall we say about these things? If God is for us, who can be against us?',
  'ROM.8.32': "He who didn't spare his own Son, but delivered him up for us all, how would he not also with him freely give us all things?",
  'ROM.8.38': 'For I am persuaded that neither death, nor life, nor angels, nor principalities, nor things present, nor things to come, nor powers,',
  'ROM.8.39': 'nor height, nor depth, nor any other created thing will be able to separate us from the love of God which is in Christ Jesus our Lord.',
};

export function getMockChapter(book, chapter) {
  const prefix = `${book}.${chapter}.`;
  return Object.entries(VERSES)
    .filter(([id]) => id.startsWith(prefix))
    .map(([osisId, text]) => ({ osisId, book, chapter, verse: parseInt(osisId.split('.')[2], 10), text }))
    .sort((a, b) => a.verse - b.verse);
}

export function hasMockData(book, chapter) {
  return Object.keys(VERSES).some(id => id.startsWith(`${book}.${chapter}.`));
}

export function getMockVerse(osisId) {
  return VERSES[osisId] ?? null;
}

export const MOCK_COVERAGE = [
  { book: 'GEN', chapter: 1 }, { book: 'GEN', chapter: 2 },
  { book: 'PSA', chapter: 23 },
  { book: 'JHN', chapter: 1 }, { book: 'JHN', chapter: 3 },
  { book: 'ROM', chapter: 8 },
];
